INSERT INTO concerts (musisi,image,description, venue, date, CategoryId) VALUES 
('CHEN','https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Chen_at_April%2C_and_a_Flower_showcase_on_April_1%2C_2019_%285%29.jpg/330px-Chen_at_April%2C_and_a_Flower_showcase_on_April_1%2C_2019_%285%29.jpg','Kim Jong-dae, better known by his stage name, Chen, is a South Korean singer and songwriter. He is a member of the South Korean-Chinese boy band Exo, its subgroup Exo-M and its subunit Exo-CBX, and participated in SM projects SM the Ballad. He is predominantly known for his role as the main vocalist of Exo.','Jakarta Convention Center','2023-12-12'),
('Tiara Andini','https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Tiara_Andini_Photoby_JodieOctora.jpg/330px-Tiara_Andini_Photoby_JodieOctora.jpg','Tiara Anugrah Eka Setyo Andini, known professionally as Tiara Andini, is an Indonesian singer and actress. She was the runner-up of the tenth season of Indonesian Idol which was broadcast by RCTI in 2019–2020. In Idol, she was known as the girl who received a titanium ticket from one of the judges.','Gelora Bung Karno','2023-11-21'),
('Mahalini','https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Mahalini_on_Opening_Ceremony_Fornas_VI.png/330px-Mahalini_on_Opening_Ceremony_Fornas_VI.png','Ni Luh Ketut Mahalini Ayu Raharja, known professionally as Mahalini, is an Indonesian singer and actress. She is known as the fifth place on the tenth season of Indonesian Idol, broadcast by the national television channels RCTI in 2019–2020.','Jakarta Convention Center','2023-12-2'),
('Lyodra','https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Lyodra_at_Rossa_25th_Year_Concert.jpg/330px-Lyodra_at_Rossa_25th_Year_Concert.jpg','Lyodra Margareta Ginting, also known mononymously as Lyodra, is an Indonesian singer and actress. She was the winner of the A3 category at the 2017 Sanremo Junior childrens international solo singing competition in Sanremo, Italy, and the winner of the tenth season of Indonesian Idol.','Paskal Hyper Square','2024-01-4'),
('Charlie Puth','https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Charlie_Puth_2017_%28cropped%29.jpg/330px-Charlie_Puth_2017_%28cropped%29.jpg','Charles Otto Puth Jr. is an American singer and songwriter. His initial exposure came through the viral success of his song videos uploaded to YouTube. Puth signed with the record label eleveneleven in 2011 after performing on The Ellen DeGeneres Show, while songwriting and producing material for other artists.','Beach International Stadium','2024-02-14'),
('Rizky Febian','https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Rizky_Febian_Performs_at_Jakarta_International_Jazz_Java_Festival_2020_%28cropped%29.png/330px-Rizky_Febian_Performs_at_Jakarta_International_Jazz_Java_Festival_2020_%28cropped%29.png','Rizky Febian Adriansyah Sutisna, professionally known as Rizky Febian, is an Indonesian singer, songwriter, actor and TV presenter. He is the eldest son of the Indonesian comedian Sule. He is famous for his single "Kesempurnaan Cinta".','Jakarta Convention Center','2023-11-20');


INSERT INTO categories (CategoryName,Kuota,Price) VALUES 
('VIP',20,2500000),
('VVIP',15,4000000),
('Reguler',50,1000000);
